package docs:calculate@0.1.0;

interface calculate{
  eval-expression: func(expr: string) -> u32;

}
world app {
    import docs:adder/add@0.1.0;
    export docs:adder/add@0.1.0;

    export calculate;
}
